### PR TITLE
in external mode, dont process anything automatically.

### PR DESCRIPTION
**Pull request by hoeken**
I haven't updated my plugins in a long time, but when I did some of the recent changes broke my external control setup.  This fixes that by checking for external control mode and exiting early if needed.

### CODE REVIEW

**Comment by htool** [comment]
Yes, sorry for getting back on this earlier.
I understand the need to not have SignalK mess with the screen, but this way it requires a plugin config change, which is clonky and requires the plugin to restart.

Better options I think would be:
 - an overwrite path boolean to activate/deactivate
 - listening for screen adjustment commands not coming from SignalK and have an option to say: 'Deactivate in case of external activity'
 
The boolean path would make it easier for control outside of the plugin config, so probably a good start.

**Comment by hoeken** [comment]
No config change is needed.  The current plugin already has the 'External / None' control mode as part of the config.  This is just an update to respect that setting.  Very simple and straightforward.

**Comment by htool** [comment]
Ok, merged.
But my point is that in order to activate the mode, you have to select it in the plugin config and save (which restarts the plugin).
That's maybe not the way one would want this to work - see my comments above.

**Comment by hoeken** [comment]
I'd rather explicitly change the setting in the configuration and know where the brightness changes are coming from.  It was very frustrating and annoying when I upgraded the plugin and it "automatically" changed away from the mode that I had set previously.

**Pull request merged**
